# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.usuario_reviewer import UsuarioReviewer
from openapi_server import util

from openapi_server.models.usuario_reviewer import UsuarioReviewer  # noqa: E501

class UsuarioReviewerArray(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, array_user_reviewer=None):  # noqa: E501
        """UsuarioReviewerArray - a model defined in OpenAPI

        :param array_user_reviewer: The array_user_reviewer of this UsuarioReviewerArray.  # noqa: E501
        :type array_user_reviewer: List[UsuarioReviewer]
        """
        self.openapi_types = {
            'array_user_reviewer': List[UsuarioReviewer]
        }

        self.attribute_map = {
            'array_user_reviewer': 'arrayUserReviewer'
        }

        self._array_user_reviewer = array_user_reviewer

    @classmethod
    def from_dict(cls, dikt) -> 'UsuarioReviewerArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsuarioReviewerArray of this UsuarioReviewerArray.  # noqa: E501
        :rtype: UsuarioReviewerArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def array_user_reviewer(self):
        """Gets the array_user_reviewer of this UsuarioReviewerArray.


        :return: The array_user_reviewer of this UsuarioReviewerArray.
        :rtype: List[UsuarioReviewer]
        """
        return self._array_user_reviewer

    @array_user_reviewer.setter
    def array_user_reviewer(self, array_user_reviewer):
        """Sets the array_user_reviewer of this UsuarioReviewerArray.


        :param array_user_reviewer: The array_user_reviewer of this UsuarioReviewerArray.
        :type array_user_reviewer: List[UsuarioReviewer]
        """
        if array_user_reviewer is None:
            raise ValueError("Invalid value for `array_user_reviewer`, must not be `None`")  # noqa: E501

        self._array_user_reviewer = array_user_reviewer
