# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UsuarioReviewer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reviewer_id=None, id=None):  # noqa: E501
        """UsuarioReviewer - a model defined in OpenAPI

        :param reviewer_id: The reviewer_id of this UsuarioReviewer.  # noqa: E501
        :type reviewer_id: int
        :param id: The id of this UsuarioReviewer.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'reviewer_id': int,
            'id': int
        }

        self.attribute_map = {
            'reviewer_id': 'reviewerId',
            'id': 'id'
        }

        self._reviewer_id = reviewer_id
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'UsuarioReviewer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsuarioReviewer of this UsuarioReviewer.  # noqa: E501
        :rtype: UsuarioReviewer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reviewer_id(self):
        """Gets the reviewer_id of this UsuarioReviewer.


        :return: The reviewer_id of this UsuarioReviewer.
        :rtype: int
        """
        return self._reviewer_id

    @reviewer_id.setter
    def reviewer_id(self, reviewer_id):
        """Sets the reviewer_id of this UsuarioReviewer.


        :param reviewer_id: The reviewer_id of this UsuarioReviewer.
        :type reviewer_id: int
        """
        if reviewer_id is None:
            raise ValueError("Invalid value for `reviewer_id`, must not be `None`")  # noqa: E501

        self._reviewer_id = reviewer_id

    @property
    def id(self):
        """Gets the id of this UsuarioReviewer.


        :return: The id of this UsuarioReviewer.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UsuarioReviewer.


        :param id: The id of this UsuarioReviewer.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
